### ISSUE TITLE
Set default thumbnail for uploaded video by time

### ISSUE THREAD

**Issue by RobinHAEVG** [haevg-rz/CF-Stream-Uploader#14]
Example: 
`curl -X POST 
-H "Authorization: Bearer $TOKEN" 
-d '{"uid": "$VIDEOID", "thumbnailTimestampPct": <pct>}' 
https://api.cloudflare.com/client/v4/accounts/$ACCOUNT/stream/$VIDEOID`

Reference: https://developers.cloudflare.com/stream/viewing-videos/displaying-thumbnails#use-case-2-setting-the-default-thumbnail-timestamp-using-the-api

**Comment by dhcgn** [comment]
`thumbnailTimestampPct` is a value between 0.0 (the first frame of the video) and 1.0 (the last frame of the video). This is particularly useful if you have videos of varying lengths. For example, you wanted the thumbnail to be the frame at the half way point of your videos, you can simply set the thumbnailTimestampPct value to 0.5.
